### ISSUE TITLE
README criteria need tightening up

### ISSUE THREAD

**Issue by Genyus** [cbfacademy/react-assessment#2]
The current criteria in [README.md](https://github.com/blackcodherbootcamp/unit04-assessment-react) aren't specific enough to support useful autograding tests, e.g.

> Load an initial set of suggested books from a local data store (JSON file) called local-books.json when the app starts up.

Need to be loaded in an element with specified id/class

> Keep a count of the number of books in your book list and display the count in the <title> tag and on the page in a h2 element.

`<h2>` element requires some identifier

> Add a search form to the home page of the app

Again, an id/class has to be provided so the tests know what to look for

etc, etc...

**Comment by tanyapowell** [comment]
@efuaakum @Genyus is this issue still valid?

**Comment by Genyus** [comment]
Nope, is obsolete. Closing.
